### ISSUE TITLE
Unhelpful error message when Docker is not running

### ISSUE THREAD

**Issue by MaxDesiatov** [nektos/act#168]
On macOS, when Docker is not running the error message doesn't say anything about the status of the Docker daemon. With the latest version of `act` installed via Homebrew the error message is:

```
% act
[Main/check-labels] 🚀  Start image=node:12.6-buster-slim
Error: unable to determine if image already exists for image "node:12.6-buster-slim"
```

The action runs normally when Docker is running, it took some time to diagnose this though. I would expect the error message to mention that the connection to the Docker daemon was not established, with a suggestion to start or to install it with a link to Docker installation instructions appropriate for the platform.

**Comment by jarektkaczyk** [comment]
2nd that, just got here with the same symptoms
thanks @MaxDesiatov for posting, helped me resolve mine quickly

**Comment by jbeveland27** [comment]
Same experience here. Additionally, I think it might be helpful to indicate in the README that Docker is both required to be installed locally and running for this to work.

Thanks to @MaxDesiatov for posting!

**Comment by chrisluedtke** [comment]
Also seeing this message.

Installed via:
```
curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
```

Other details:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

$ docker --version
Docker version 19.03.8, build afacb8b7f0
```

**Comment by AdrianoCahete** [comment]
Same on Windows 10.

**Comment by neilswinton** [comment]
I'm seeing this while running inside in a container.  In my container, docker is exposed using TCP port 2375.  The code seems to look for /var/run/docker.sock even when DOCKER_HOST=host.docker.internal:2375.  Since there's no /var/run/docker.sock the listing of images fails along with all other access to docker.  Docker commands succeed because they honor DOCKER_HOST.  I realize this is not a mainstream issue...

**Comment by cplee** [comment]
fixed by https://github.com/nektos/act/commit/6c4e7b9fdedeeeb1eda78cefaff55750033d1327

**Comment by kiptoomm** [comment]
For anyone like me who was still getting this error message, ensure [docker is installed and running](https://stackoverflow.com/questions/40523307/brew-install-docker-does-not-include-docker-engine)
