### ISSUE TITLE
'needs' is not defined

### ISSUE THREAD

**Issue by kochetkovIT** [nektos/act#295]
Error `ERRO[0002] Unable to interpolate string 'echo ${{ needs.pre.output1 }}' - [ReferenceError: 'needs' is not defined]` when try to following workflow: 
```
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::set-env name=VAR1::value1'
    outputs:
      output1: ${{ env.VAR1 }}

  job1:
    runs-on: ubuntu-latest
    needs: [pre]
    steps:
      - run: echo ${{ needs.pre.outputs.output1 }}
```

This syntax is working in workflow ran by Github Actions, as we do use it in our project's CI.

**Comment by snipebin** [comment]
+1

**Comment by Nilegfx** [comment]
any workaround for this?

**Comment by davidwestberry** [comment]
This feature would be really helpful

**Comment by cgr71ii** [comment]
I don't know when this feature was implemented, but is working right now. What i don't achieve is to have the same environment from one job to other (I'm installing `sudo` first, and in the job which contains `needs` does not recognizes `sudo`). I guess that I'm doing something wrong, since I think that doesn't makes much sense to implement `needs` without environment sharing. Any clue about this?

**Comment by matiasalbarello** [comment]
+1

**Comment by njimenezotto** [comment]
+1

**Comment by seru1us** [comment]
+1

**Comment by anthonykawa** [comment]
+1

**Comment by ch1seL** [comment]
+1

**Comment by abelcha** [comment]
+1

**Comment by almahmoud** [comment]
+1

**Comment by gcoban** [comment]
Community needs "needs" :)

**Comment by gakonst** [comment]
+1

**Comment by Joshuapwilley** [comment]
This is a huge blocker for us. The "needs" parameter enables proper, efficient parallel jobs to be run that have a common set of steps that need to be run for all of them.

We have a number of applications that build for multiple environments but share several common steps. Without being able to use the "needs" option, we have to resort to duplicating steps and waiting on things to run serially which is FAR less than ideal.

**Comment by agentschmitt** [comment]
We are also using the needs parameter in many workflows, but this breaks usage of act and we cant test locally anymore.
Adding support for this would be really nice.

**Comment by hcguersoy-oc** [comment]
Unfortunately here the same: needing `needs` but it blocks simply using _act_ for our development process.

**Comment by adamthedog** [comment]
@hcguersoy-oc
Just wantted to let you know; the fix was merged yesterday! :) (see: #629 as per `mergify` update)

**Comment by jacksoncougar** [comment]
When I run this example [https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-8]
```yml
name: Diff AccessDB
on: [pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
```
Then I am getting this error in the latest `@master` version when I run act.

'''
ERRO[0003] Unable to interpolate string '${{ steps.step2.outputs.test }}' - [TypeError: Cannot access member 'outputs' of undefined]
'''

Is this a known limitation?

**Comment by craigtubb57** [comment]
I am seeing the same. It seems to only work with the first step of each job.

**Comment by Steph0** [comment]
Hope the next release is soon with this. Have a hard time convincing my team to think ACT first because of that :)
Thanks for the work on act tought, i love it

**Comment by karisalonen** [comment]
+1

**Comment by cplee** [comment]
@Steph0 - just released https://github.com/nektos/act/releases/tag/v0.2.24

**Comment by Steph0** [comment]
Love it thanks !

**Comment by dirablue** [comment]
> When I run this example https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-8
> 
> ```yaml
> name: Diff AccessDB
> on: [pull_request]
> 
> jobs:
>   job1:
>     runs-on: ubuntu-latest
>     # Map a step output to a job output
>     outputs:
>       output1: ${{ steps.step1.outputs.test }}
>       output2: ${{ steps.step2.outputs.test }}
>     steps:
>       - id: step1
>         run: echo "::set-output name=test::hello"
>       - id: step2
>         run: echo "::set-output name=test::world"
>   job2:
>     runs-on: ubuntu-latest
>     needs: job1
>     steps:
>       - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
> ```
> 
> Then I am getting this error in the latest `@master` version when I run act.
> 
> > ERRO[0003] Unable to interpolate string '${{ steps.step2.outputs.test }}' - [TypeError: Cannot access member 'outputs' of undefined]
> 
> Is this a known limitation?

@cplee 
hi, is there any update on this.. ?

**Comment by catthehacker** [comment]
No

**Comment by littleamigo** [comment]
I have tried your test workflow from https://github.com/nektos/act/pull/629 > pkg/model/workflow_test.go and it works :)
```
[test/test2] ⭐  Run test2_1
| some-a_value
| some-b-value
[test/test2]   ✅  Success - test2_1
```

Then I inserted a single step '**doSomething**' before the step with the output assignments and it failed, i.e. all output variables are empty :(
```
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - id: doSomething
        run: echo "do something..."
      - id: test1_1
        run: |
          echo "::set-output name=a_key::some-a_value"
          echo "::set-output name=b-key::some-b-value"
    outputs:
      some_a_key: ${{ steps.test1_1.outputs.a_key }}
      some-b-key: ${{ steps.test1_1.outputs.b-key }}
  test2:
    runs-on: ubuntu-latest
    needs:
      - test1
    steps:
      - name: test2_1
        run: |
          echo "${{ needs.test1.outputs.some_a_key }}"
          echo "${{ needs.test1.outputs.some-b-key }}"
```

```
[test/test2] ⭐  Run test2_1
workflow-test/workflow/0] user=
|
|
[test/test2]   ✅  Success - test2_1
```
Can this bug be fixed soon?

**Comment by nomadme** [comment]
Same problem, still getting empty output variables from step.

`act version 0.2.25`

**Comment by ZauberNerd** [comment]
As far as I can see, all the example workflows posted here work fine with `0.2.25`.

@littleamigo that sounds like: https://github.com/nektos/act/issues/758 which has been fixed in `0.2.25` (see the release notes: https://github.com/nektos/act/releases/tag/v0.2.25 and note commit ff8b1df).

**Comment by Bouncner** [comment]
Still facing this issue with `[TypeError: Cannot access member 'outputs' of undefined]` and version 0.2.25. On GitHub, the workflow runs just fine.

**Comment by ZauberNerd** [comment]
@Bouncner please provide us with a minimal reproducible workflow.

**Comment by Bouncner** [comment]
I tried, but I am not able to reproduce it without the large setup. Interestingly, it happens in the **step after the step that sets the output**.

`id: core_client_counts` sets the outputs and then act crashes with:
```
| FAILED: hyrise/src/lib/CMakeFiles/resourceLink
| cd /home/Martin.Boissier/encoding_selection_private/encoding_plugin/rel/hyrise/src/lib && ln -fs /home/Martin.Boissier/encoding_selection_private/encoding_plugin/rel/../resources /home/Martin.Boissier/encoding_selection_private/encoding_plugin/rel/
| ln: /home/Martin.Boissier/encoding_selection_private/encoding_plugin/rel/resources: cannot overwrite directory
[3/8] cd /home/Martin.Boissier/encoding_selection_private/encoding_plugin/rel/hyrise/src/lib && /usr/bin/cmake -DGIT_FUNCTION=DoMonitoring -DGIT_WORKING_DIR=/home/Martin.Boissier/encoding_selection_private/encoding_plugin/hyrise/src/lib -Dpre_configure_file=/home/Martin.Boissier/encoding_selection_private/encoding_plugin/hyrise/src/lib/version.hpp.in -Dpost_configure_file=/home/Martin.Boissier/encoding_selection_private/encoding_plugin/rel/version.hpp -P /home/Martin.Boissier/encoding_selection_private/encoding_plugin/hyrise/cmake/git_watcher.cmake
| ninja: build stopped: subcommand failed.
[Main/Hyrise - Full calibration and evaluation pipeline]   ❌  Failure - Build release server and plugins
ERRO[0205] Unable to interpolate string '${{ steps.calibration.outputs.calibration_run }}' - [TypeError: Cannot access member 'outputs' of undefined]
Error: exit with `FAILURE`: 1
```
This is during the compilation, which is the step after the output setting.

https://github.com/hyrise/encoding_selection/blob/9c5d3082efd444aa6f12091793d2bdb289d695ef/.github/workflows/haupt.yml#L69

**Comment by ZauberNerd** [comment]
@Bouncner this seems to be **an aftereffect of a previous step failing**. You can see in your output above that the `Build release server and plugins` step failed - fix this and the outputs should work.

You're also correct, that here the behaviour of act differs from GitHub Actions, but once you fix the above error it should work.

Here's an example workflow that illustrates the problem:
```
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - run: exit 1 # removing this line makes the workflow succeed
      - id: step2
        run: echo "::set-output name=test::world"
```

**Comment by Bouncner** [comment]
Argh, been blind. I reused the setup and didn't realize that this caused the compilation error. Sorry.

If I had a which, an more telling error message would be awesome.
